# generated by datamodel-codegen:
#   filename:  muhammed15.json
#   timestamp: 2025-04-05T03:02:44+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class Locations(BaseModel):
    latitude: float
    longitude: float
    geometry: str


class SimulationConfig(BaseModel):
    start_year: int
    end_year: int
    site_file_name: str
    labeling_type: int
    labeling_year: int
    microcosm: int
    co2_systems: int
    ph_shift: int
    soil_warming: int
    n_input_scalar_option: int
    omad_scalar_option: int
    climate_scalar_option: int
    initial_system: int
    initial_crop: str
    initial_tree: str


class Date(BaseModel):
    year: int
    month: int
    day: int


class ManagementDetail(BaseModel):
    date: Date
    event_type: str
    event_set: str


class ManagementBlock(BaseModel):
    block_number: int
    end_year: int
    year_repeats: int
    start_year: int
    output_month: float
    output_interval: float
    weather_choice: str
    weather_file: str
    management_details: List[ManagementDetail]


class Scenarios(BaseModel):
    simulation_config: SimulationConfig
    management_blocks: List[ManagementBlock]


class Layer1(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer2(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer3(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer4(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer5(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer6(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer7(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer8(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer9(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer10(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer11(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer12(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer13(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Layer14(BaseModel):
    thickness: float
    upper_depth: float
    lower_depth: float
    bulk_density: float
    field_capacity: float
    wilting_point: float
    evap_coeff: float
    fraction_of_roots: float
    sand_fraction: float
    clay_fraction: float
    organic_matter_fraction: float
    deltamin: float
    ksat: float
    pH: float


class Soil(BaseModel):
    layer_1: Layer1
    layer_2: Layer2
    layer_3: Layer3
    layer_4: Layer4
    layer_5: Layer5
    layer_6: Layer6
    layer_7: Layer7
    layer_8: Layer8
    layer_9: Layer9
    layer_10: Layer10
    layer_11: Layer11
    layer_12: Layer12
    layer_13: Layer13
    layer_14: Layer14


class ClimateParameters(BaseModel):
    precip_1_: float = Field(..., alias='precip(1)')
    precip_2_: float = Field(..., alias='precip(2)')
    precip_3_: float = Field(..., alias='precip(3)')
    precip_4_: float = Field(..., alias='precip(4)')
    precip_5_: float = Field(..., alias='precip(5)')
    precip_6_: float = Field(..., alias='precip(6)')
    precip_7_: float = Field(..., alias='precip(7)')
    precip_8_: float = Field(..., alias='precip(8)')
    precip_9_: float = Field(..., alias='precip(9)')
    precip_10_: float = Field(..., alias='precip(10)')
    precip_11_: float = Field(..., alias='precip(11)')
    precip_12_: float = Field(..., alias='precip(12)')
    prcstd_1_: float = Field(..., alias='prcstd(1)')
    prcstd_2_: float = Field(..., alias='prcstd(2)')
    prcstd_3_: float = Field(..., alias='prcstd(3)')
    prcstd_4_: float = Field(..., alias='prcstd(4)')
    prcstd_5_: float = Field(..., alias='prcstd(5)')
    prcstd_6_: float = Field(..., alias='prcstd(6)')
    prcstd_7_: float = Field(..., alias='prcstd(7)')
    prcstd_8_: float = Field(..., alias='prcstd(8)')
    prcstd_9_: float = Field(..., alias='prcstd(9)')
    prcstd_10_: float = Field(..., alias='prcstd(10)')
    prcstd_11_: float = Field(..., alias='prcstd(11)')
    prcstd_12_: float = Field(..., alias='prcstd(12)')
    prcskw_1_: float = Field(..., alias='prcskw(1)')
    prcskw_2_: float = Field(..., alias='prcskw(2)')
    prcskw_3_: float = Field(..., alias='prcskw(3)')
    prcskw_4_: float = Field(..., alias='prcskw(4)')
    prcskw_5_: float = Field(..., alias='prcskw(5)')
    prcskw_6_: float = Field(..., alias='prcskw(6)')
    prcskw_7_: float = Field(..., alias='prcskw(7)')
    prcskw_8_: float = Field(..., alias='prcskw(8)')
    prcskw_9_: float = Field(..., alias='prcskw(9)')
    prcskw_10_: float = Field(..., alias='prcskw(10)')
    prcskw_11_: float = Field(..., alias='prcskw(11)')
    prcskw_12_: float = Field(..., alias='prcskw(12)')
    tmn2m_1_: float = Field(..., alias='tmn2m(1)')
    tmn2m_2_: float = Field(..., alias='tmn2m(2)')
    tmn2m_3_: float = Field(..., alias='tmn2m(3)')
    tmn2m_4_: float = Field(..., alias='tmn2m(4)')
    tmn2m_5_: float = Field(..., alias='tmn2m(5)')
    tmn2m_6_: float = Field(..., alias='tmn2m(6)')
    tmn2m_7_: float = Field(..., alias='tmn2m(7)')
    tmn2m_8_: float = Field(..., alias='tmn2m(8)')
    tmn2m_9_: float = Field(..., alias='tmn2m(9)')
    tmn2m_10_: float = Field(..., alias='tmn2m(10)')
    tmn2m_11_: float = Field(..., alias='tmn2m(11)')
    tmn2m_12_: float = Field(..., alias='tmn2m(12)')
    tmx2m_1_: float = Field(..., alias='tmx2m(1)')
    tmx2m_2_: float = Field(..., alias='tmx2m(2)')
    tmx2m_3_: float = Field(..., alias='tmx2m(3)')
    tmx2m_4_: float = Field(..., alias='tmx2m(4)')
    tmx2m_5_: float = Field(..., alias='tmx2m(5)')
    tmx2m_6_: float = Field(..., alias='tmx2m(6)')
    tmx2m_7_: float = Field(..., alias='tmx2m(7)')
    tmx2m_8_: float = Field(..., alias='tmx2m(8)')
    tmx2m_9_: float = Field(..., alias='tmx2m(9)')
    tmx2m_10_: float = Field(..., alias='tmx2m(10)')
    tmx2m_11_: float = Field(..., alias='tmx2m(11)')
    tmx2m_12_: float = Field(..., alias='tmx2m(12)')


class SiteAndControlParameters(BaseModel):
    ivauto: int
    nelem: int
    sitlat: float
    sitlng: float
    sand: float
    silt: float
    clay: float
    rock: int
    bulkd: float
    nlayer: int
    nlaypg: int
    drain: float
    basef: float
    stormf: int
    precro: int
    fracro: float
    swflag: int
    awilt_1_: float = Field(..., alias='awilt(1)')
    awilt_2_: float = Field(..., alias='awilt(2)')
    awilt_3_: float = Field(..., alias='awilt(3)')
    awilt_4_: float = Field(..., alias='awilt(4)')
    awilt_5_: float = Field(..., alias='awilt(5)')
    awilt_6_: float = Field(..., alias='awilt(6)')
    awilt_7_: float = Field(..., alias='awilt(7)')
    awilt_8_: float = Field(..., alias='awilt(8)')
    awilt_9_: float = Field(..., alias='awilt(9)')
    awilt_10_: float = Field(..., alias='awilt(10)')
    afiel_1_: float = Field(..., alias='afiel(1)')
    afiel_2_: float = Field(..., alias='afiel(2)')
    afiel_3_: float = Field(..., alias='afiel(3)')
    afiel_4_: float = Field(..., alias='afiel(4)')
    afiel_5_: float = Field(..., alias='afiel(5)')
    afiel_6_: float = Field(..., alias='afiel(6)')
    afiel_7_: float = Field(..., alias='afiel(7)')
    afiel_8_: float = Field(..., alias='afiel(8)')
    afiel_9_: float = Field(..., alias='afiel(9)')
    afiel_10_: int = Field(..., alias='afiel(10)')
    ph: float
    pslsrb: int
    sorpmx: int


class ExternalNutrientInputParameters(BaseModel):
    epnfa_1_: float = Field(..., alias='epnfa(1)')
    epnfa_2_: float = Field(..., alias='epnfa(2)')
    epnfs_1_: int = Field(..., alias='epnfs(1)')
    epnfs_2_: float = Field(..., alias='epnfs(2)')
    satmos_1_: int = Field(..., alias='satmos(1)')
    satmos_2_: int = Field(..., alias='satmos(2)')
    sirri: int


class OrganicMatterInitialValues(BaseModel):
    som1ci_1_1_: float = Field(..., alias='som1ci(1,1)')
    som1ci_1_2_: int = Field(..., alias='som1ci(1,2)')
    som1ci_2_1_: float = Field(..., alias='som1ci(2,1)')
    som1ci_2_2_: int = Field(..., alias='som1ci(2,2)')
    som2ci_1_1_: float = Field(..., alias='som2ci(1,1)')
    som2ci_1_2_: int = Field(..., alias='som2ci(1,2)')
    som2ci_2_1_: float = Field(..., alias='som2ci(2,1)')
    som2ci_2_2_: int = Field(..., alias='som2ci(2,2)')
    som3ci_1_: float = Field(..., alias='som3ci(1)')
    som3ci_2_: int = Field(..., alias='som3ci(2)')
    rces1_1_1_: float = Field(..., alias='rces1(1,1)')
    rces1_1_2_: int = Field(..., alias='rces1(1,2)')
    rces1_1_3_: int = Field(..., alias='rces1(1,3)')
    rces1_2_1_: float = Field(..., alias='rces1(2,1)')
    rces1_2_2_: int = Field(..., alias='rces1(2,2)')
    rces1_2_3_: int = Field(..., alias='rces1(2,3)')
    rces2_1_1_: float = Field(..., alias='rces2(1,1)')
    rces2_1_2_: int = Field(..., alias='rces2(1,2)')
    rces2_1_3_: int = Field(..., alias='rces2(1,3)')
    rces2_2_1_: float = Field(..., alias='rces2(2,1)')
    rces2_2_2_: int = Field(..., alias='rces2(2,2)')
    rces2_2_3_: int = Field(..., alias='rces2(2,3)')
    rces3_1_: float = Field(..., alias='rces3(1)')
    rces3_2_: int = Field(..., alias='rces3(2)')
    rces3_3_: int = Field(..., alias='rces3(3)')
    clittr_1_1_: float = Field(..., alias='clittr(1,1)')
    clittr_1_2_: int = Field(..., alias='clittr(1,2)')
    clittr_2_1_: float = Field(..., alias='clittr(2,1)')
    clittr_2_2_: int = Field(..., alias='clittr(2,2)')
    rcelit_1_1_: float = Field(..., alias='rcelit(1,1)')
    rcelit_1_2_: int = Field(..., alias='rcelit(1,2)')
    rcelit_1_3_: int = Field(..., alias='rcelit(1,3)')
    rcelit_2_1_: float = Field(..., alias='rcelit(2,1)')
    rcelit_2_2_: int = Field(..., alias='rcelit(2,2)')
    rcelit_2_3_: int = Field(..., alias='rcelit(2,3)')
    aglcis_1_: float = Field(..., alias='aglcis(1)')
    aglcis_2_: int = Field(..., alias='aglcis(2)')
    aglive_1_: float = Field(..., alias='aglive(1)')
    aglive_2_: int = Field(..., alias='aglive(2)')
    aglive_3_: int = Field(..., alias='aglive(3)')
    bglcis_1_: float = Field(..., alias='bglcis(1)')
    bglcis_2_: int = Field(..., alias='bglcis(2)')
    bglive_1_: float = Field(..., alias='bglive(1)')
    bglive_2_: int = Field(..., alias='bglive(2)')
    bglive_3_: int = Field(..., alias='bglive(3)')
    stdcis_1_: float = Field(..., alias='stdcis(1)')
    stdcis_2_: int = Field(..., alias='stdcis(2)')
    stdede_1_: float = Field(..., alias='stdede(1)')
    stdede_2_: int = Field(..., alias='stdede(2)')
    stdede_3_: int = Field(..., alias='stdede(3)')


class ForestOrganicMatterInitialParameters(BaseModel):
    rlvcis_1_: int = Field(..., alias='rlvcis(1)')
    rlvcis_2_: int = Field(..., alias='rlvcis(2)')
    rleave_1_: int = Field(..., alias='rleave(1)')
    rleave_2_: int = Field(..., alias='rleave(2)')
    rleave_3_: int = Field(..., alias='rleave(3)')
    fbrcis_1_: int = Field(..., alias='fbrcis(1)')
    fbrcis_2_: int = Field(..., alias='fbrcis(2)')
    fbrche_1_: int = Field(..., alias='fbrche(1)')
    fbrche_2_: int = Field(..., alias='fbrche(2)')
    fbrche_3_: int = Field(..., alias='fbrche(3)')
    rlwcis_1_: int = Field(..., alias='rlwcis(1)')
    rlwcis_2_: int = Field(..., alias='rlwcis(2)')
    rlwode_1_: int = Field(..., alias='rlwode(1)')
    rlwode_2_: int = Field(..., alias='rlwode(2)')
    rlwode_3_: int = Field(..., alias='rlwode(3)')
    frtcis_1_: int = Field(..., alias='frtcis(1)')
    frtcis_2_: int = Field(..., alias='frtcis(2)')
    froote_1_: int = Field(..., alias='froote(1)')
    froote_2_: int = Field(..., alias='froote(2)')
    froote_3_: int = Field(..., alias='froote(3)')
    crtcis_1_: int = Field(..., alias='crtcis(1)')
    crtcis_2_: int = Field(..., alias='crtcis(2)')
    croote_1_: int = Field(..., alias='croote(1)')
    croote_2_: int = Field(..., alias='croote(2)')
    croote_3_: int = Field(..., alias='croote(3)')
    wd1cis_1_: int = Field(..., alias='wd1cis(1)')
    wd1cis_2_: int = Field(..., alias='wd1cis(2)')
    wd2cis_1_: int = Field(..., alias='wd2cis(1)')
    wd2cis_2_: int = Field(..., alias='wd2cis(2)')
    wd3cis_1_: int = Field(..., alias='wd3cis(1)')
    wd3cis_2_: int = Field(..., alias='wd3cis(2)')


class MineralInitialParameters(BaseModel):
    minerl_1_1_: float = Field(..., alias='minerl(1,1)')
    minerl_2_1_: float = Field(..., alias='minerl(2,1)')
    minerl_3_1_: float = Field(..., alias='minerl(3,1)')
    minerl_4_1_: float = Field(..., alias='minerl(4,1)')
    minerl_5_1_: float = Field(..., alias='minerl(5,1)')
    minerl_6_1_: float = Field(..., alias='minerl(6,1)')
    minerl_7_1_: float = Field(..., alias='minerl(7,1)')
    minerl_8_1_: int = Field(..., alias='minerl(8,1)')
    minerl_9_1_: int = Field(..., alias='minerl(9,1)')
    minerl_10_1_: int = Field(..., alias='minerl(10,1)')
    minerl_1_2_: float = Field(..., alias='minerl(1,2)')
    minerl_2_2_: int = Field(..., alias='minerl(2,2)')
    minerl_3_2_: int = Field(..., alias='minerl(3,2)')
    minerl_4_2_: int = Field(..., alias='minerl(4,2)')
    minerl_5_2_: int = Field(..., alias='minerl(5,2)')
    minerl_6_2_: int = Field(..., alias='minerl(6,2)')
    minerl_7_2_: int = Field(..., alias='minerl(7,2)')
    minerl_8_2_: int = Field(..., alias='minerl(8,2)')
    minerl_9_2_: int = Field(..., alias='minerl(9,2)')
    minerl_10_2_: int = Field(..., alias='minerl(10,2)')
    minerl_1_3_: float = Field(..., alias='minerl(1,3)')
    minerl_2_3_: int = Field(..., alias='minerl(2,3)')
    minerl_3_3_: int = Field(..., alias='minerl(3,3)')
    minerl_4_3_: int = Field(..., alias='minerl(4,3)')
    minerl_5_3_: int = Field(..., alias='minerl(5,3)')
    minerl_6_3_: int = Field(..., alias='minerl(6,3)')
    minerl_7_3_: int = Field(..., alias='minerl(7,3)')
    minerl_8_3_: int = Field(..., alias='minerl(8,3)')
    minerl_9_3_: int = Field(..., alias='minerl(9,3)')
    minerl_10_3_: int = Field(..., alias='minerl(10,3)')
    parent_1_: int = Field(..., alias='parent(1)')
    parent_2_: int = Field(..., alias='parent(2)')
    parent_3_: int = Field(..., alias='parent(3)')
    secndy_1_: int = Field(..., alias='secndy(1)')
    secndy_2_: int = Field(..., alias='secndy(2)')
    secndy_3_: int = Field(..., alias='secndy(3)')
    occlud: int


class WaterInitialParameters(BaseModel):
    rwcf_1_: float = Field(..., alias='rwcf(1)')
    rwcf_2_: float = Field(..., alias='rwcf(2)')
    rwcf_3_: float = Field(..., alias='rwcf(3)')
    rwcf_4_: float = Field(..., alias='rwcf(4)')
    rwcf_5_: float = Field(..., alias='rwcf(5)')
    rwcf_6_: float = Field(..., alias='rwcf(6)')
    rwcf_7_: int = Field(..., alias='rwcf(7)')
    rwcf_8_: int = Field(..., alias='rwcf(8)')
    rwcf_9_: int = Field(..., alias='rwcf(9)')
    rwcf_10_: int = Field(..., alias='rwcf(10)')
    snlq: int
    snow: int


class Site(BaseModel):
    climate_parameters: ClimateParameters
    site_and_control_parameters: SiteAndControlParameters
    external_nutrient_input_parameters: ExternalNutrientInputParameters
    organic_matter_initial_values: OrganicMatterInitialValues
    forest_organic_matter_initial_parameters: ForestOrganicMatterInitialParameters
    mineral_initial_parameters: MineralInitialParameters
    water_initial_parameters: WaterInitialParameters


class Weather(BaseModel):
    header: List[str]
    value: List[List[float]]


class SiteConfigs(BaseModel):
    soil: Soil
    site: Site
    weather: Weather
    site_extension: Dict[str, Any]


class ALMOND(BaseModel):
    decid: float
    prdx_2_: float = Field(..., alias='prdx(2)')
    ppdf_1_: float = Field(..., alias='ppdf(1)')
    ppdf_2_: float = Field(..., alias='ppdf(2)')
    ppdf_3_: float = Field(..., alias='ppdf(3)')
    ppdf_4_: float = Field(..., alias='ppdf(4)')
    cerfor_1_1_1_: float = Field(..., alias='cerfor(1,1,1)')
    cerfor_1_1_2_: float = Field(..., alias='cerfor(1,1,2)')
    cerfor_1_1_3_: float = Field(..., alias='cerfor(1,1,3)')
    cerfor_1_2_1_: float = Field(..., alias='cerfor(1,2,1)')
    cerfor_1_2_2_: float = Field(..., alias='cerfor(1,2,2)')
    cerfor_1_2_3_: float = Field(..., alias='cerfor(1,2,3)')
    cerfor_1_3_1_: float = Field(..., alias='cerfor(1,3,1)')
    cerfor_1_3_2_: float = Field(..., alias='cerfor(1,3,2)')
    cerfor_1_3_3_: float = Field(..., alias='cerfor(1,3,3)')
    cerfor_1_4_1_: float = Field(..., alias='cerfor(1,4,1)')
    cerfor_1_4_2_: float = Field(..., alias='cerfor(1,4,2)')
    cerfor_1_4_3_: float = Field(..., alias='cerfor(1,4,3)')
    cerfor_1_5_1_: float = Field(..., alias='cerfor(1,5,1)')
    cerfor_1_5_2_: float = Field(..., alias='cerfor(1,5,2)')
    cerfor_1_5_3_: float = Field(..., alias='cerfor(1,5,3)')
    cerfor_1_6_1_: float = Field(..., alias='cerfor(1,6,1)')
    cerfor_1_6_2_: float = Field(..., alias='cerfor(1,6,2)')
    cerfor_1_6_3_: float = Field(..., alias='cerfor(1,6,3)')
    cerfor_2_1_1_: float = Field(..., alias='cerfor(2,1,1)')
    cerfor_2_1_2_: float = Field(..., alias='cerfor(2,1,2)')
    cerfor_2_1_3_: float = Field(..., alias='cerfor(2,1,3)')
    cerfor_2_2_1_: float = Field(..., alias='cerfor(2,2,1)')
    cerfor_2_2_2_: float = Field(..., alias='cerfor(2,2,2)')
    cerfor_2_2_3_: float = Field(..., alias='cerfor(2,2,3)')
    cerfor_2_3_1_: float = Field(..., alias='cerfor(2,3,1)')
    cerfor_2_3_2_: float = Field(..., alias='cerfor(2,3,2)')
    cerfor_2_3_3_: float = Field(..., alias='cerfor(2,3,3)')
    cerfor_2_4_1_: float = Field(..., alias='cerfor(2,4,1)')
    cerfor_2_4_2_: float = Field(..., alias='cerfor(2,4,2)')
    cerfor_2_4_3_: float = Field(..., alias='cerfor(2,4,3)')
    cerfor_2_5_1_: float = Field(..., alias='cerfor(2,5,1)')
    cerfor_2_5_2_: float = Field(..., alias='cerfor(2,5,2)')
    cerfor_2_5_3_: float = Field(..., alias='cerfor(2,5,3)')
    cerfor_2_6_1_: float = Field(..., alias='cerfor(2,6,1)')
    cerfor_2_6_2_: float = Field(..., alias='cerfor(2,6,2)')
    cerfor_2_6_3_: float = Field(..., alias='cerfor(2,6,3)')
    cerfor_3_1_1_: float = Field(..., alias='cerfor(3,1,1)')
    cerfor_3_1_2_: float = Field(..., alias='cerfor(3,1,2)')
    cerfor_3_1_3_: float = Field(..., alias='cerfor(3,1,3)')
    cerfor_3_2_1_: float = Field(..., alias='cerfor(3,2,1)')
    cerfor_3_2_2_: float = Field(..., alias='cerfor(3,2,2)')
    cerfor_3_2_3_: float = Field(..., alias='cerfor(3,2,3)')
    cerfor_3_3_1_: float = Field(..., alias='cerfor(3,3,1)')
    cerfor_3_3_2_: float = Field(..., alias='cerfor(3,3,2)')
    cerfor_3_3_3_: float = Field(..., alias='cerfor(3,3,3)')
    cerfor_3_4_1_: float = Field(..., alias='cerfor(3,4,1)')
    cerfor_3_4_2_: float = Field(..., alias='cerfor(3,4,2)')
    cerfor_3_4_3_: float = Field(..., alias='cerfor(3,4,3)')
    cerfor_3_5_1_: float = Field(..., alias='cerfor(3,5,1)')
    cerfor_3_5_2_: float = Field(..., alias='cerfor(3,5,2)')
    cerfor_3_5_3_: float = Field(..., alias='cerfor(3,5,3)')
    cerfor_3_6_1_: float = Field(..., alias='cerfor(3,6,1)')
    cerfor_3_6_2_: float = Field(..., alias='cerfor(3,6,2)')
    cerfor_3_6_3_: float = Field(..., alias='cerfor(3,6,3)')
    decw1: float
    decw2: float
    decw3: float
    fcfrac_1_1_: float = Field(..., alias='fcfrac(1,1)')
    fcfrac_2_1_: float = Field(..., alias='fcfrac(2,1)')
    fcfrac_3_1_: float = Field(..., alias='fcfrac(3,1)')
    fcfrac_4_1_: float = Field(..., alias='fcfrac(4,1)')
    fcfrac_5_1_: float = Field(..., alias='fcfrac(5,1)')
    fcfrac_6_1_: float = Field(..., alias='fcfrac(6,1)')
    fcfrac_1_2_: float = Field(..., alias='fcfrac(1,2)')
    fcfrac_2_2_: float = Field(..., alias='fcfrac(2,2)')
    fcfrac_3_2_: float = Field(..., alias='fcfrac(3,2)')
    fcfrac_4_2_: float = Field(..., alias='fcfrac(4,2)')
    fcfrac_5_2_: float = Field(..., alias='fcfrac(5,2)')
    fcfrac_6_2_: float = Field(..., alias='fcfrac(6,2)')
    tfrtcn_1_: float = Field(..., alias='tfrtcn(1)')
    tfrtcn_2_: float = Field(..., alias='tfrtcn(2)')
    tfrtcw_1_: float = Field(..., alias='tfrtcw(1)')
    tfrtcw_2_: float = Field(..., alias='tfrtcw(2)')
    fnftim: float
    fngddl_1_: float = Field(..., alias='fngddl(1)')
    fngddl_2_: float = Field(..., alias='fngddl(2)')
    fngddl_3_: float = Field(..., alias='fngddl(3)')
    leafdr_1_: float = Field(..., alias='leafdr(1)')
    leafdr_2_: float = Field(..., alias='leafdr(2)')
    leafdr_3_: float = Field(..., alias='leafdr(3)')
    leafdr_4_: float = Field(..., alias='leafdr(4)')
    leafdr_5_: float = Field(..., alias='leafdr(5)')
    leafdr_6_: float = Field(..., alias='leafdr(6)')
    leafdr_7_: float = Field(..., alias='leafdr(7)')
    leafdr_8_: float = Field(..., alias='leafdr(8)')
    leafdr_9_: float = Field(..., alias='leafdr(9)')
    leafdr_10_: float = Field(..., alias='leafdr(10)')
    leafdr_11_: float = Field(..., alias='leafdr(11)')
    leafdr_12_: float = Field(..., alias='leafdr(12)')
    btolai: float
    klai: float
    laitop: float
    maxlai: float
    maxldr: float
    forrtf_1_: float = Field(..., alias='forrtf(1)')
    forrtf_2_: float = Field(..., alias='forrtf(2)')
    forrtf_3_: float = Field(..., alias='forrtf(3)')
    sapk: float
    swold: float
    wdlig_1_: float = Field(..., alias='wdlig(1)')
    wdlig_2_: float = Field(..., alias='wdlig(2)')
    wdlig_3_: float = Field(..., alias='wdlig(3)')
    wdlig_4_: float = Field(..., alias='wdlig(4)')
    wdlig_5_: float = Field(..., alias='wdlig(5)')
    wdlig_6_: float = Field(..., alias='wdlig(6)')
    wooddr_1_: float = Field(..., alias='wooddr(1)')
    wooddr_2_: float = Field(..., alias='wooddr(2)')
    wooddr_3_: float = Field(..., alias='wooddr(3)')
    wooddr_4_: float = Field(..., alias='wooddr(4)')
    wooddr_5_: float = Field(..., alias='wooddr(5)')
    wooddr_6_: float = Field(..., alias='wooddr(6)')
    wooddr_7_: float = Field(..., alias='wooddr(7)')
    wrdsrfc: float
    wmrtfrac: float
    snfxmx_2_: float = Field(..., alias='snfxmx(2)')
    del13c: float
    co2ipr_2_: float = Field(..., alias='co2ipr(2)')
    co2itr_2_: float = Field(..., alias='co2itr(2)')
    co2ice_2_1_1_: float = Field(..., alias='co2ice(2,1,1)')
    co2ice_2_1_2_: float = Field(..., alias='co2ice(2,1,2)')
    co2ice_2_1_3_: float = Field(..., alias='co2ice(2,1,3)')
    co2ice_2_2_1_: float = Field(..., alias='co2ice(2,2,1)')
    co2ice_2_2_2_: float = Field(..., alias='co2ice(2,2,2)')
    co2ice_2_2_3_: float = Field(..., alias='co2ice(2,2,3)')
    co2irs_2_: float = Field(..., alias='co2irs(2)')
    basfc2: float
    basfct: float
    sitpot: float
    maxnp: float
    fkmrspmx_1_: float = Field(..., alias='fkmrspmx(1)')
    fkmrspmx_2_: float = Field(..., alias='fkmrspmx(2)')
    fkmrspmx_3_: float = Field(..., alias='fkmrspmx(3)')
    fkmrspmx_4_: float = Field(..., alias='fkmrspmx(4)')
    fkmrspmx_5_: float = Field(..., alias='fkmrspmx(5)')
    fkmrspmx_6_: float = Field(..., alias='fkmrspmx(6)')
    fkmrspmx_7_: float = Field(..., alias='fkmrspmx(7)')
    fmrsplai_1_: float = Field(..., alias='fmrsplai(1)')
    fmrsplai_2_: float = Field(..., alias='fmrsplai(2)')
    fmrsplai_3_: float = Field(..., alias='fmrsplai(3)')
    fmrsplai_4_: float = Field(..., alias='fmrsplai(4)')
    fmrsplai_5_: float = Field(..., alias='fmrsplai(5)')
    fmrsplai_6_: float = Field(..., alias='fmrsplai(6)')
    fmrsplai_7_: float = Field(..., alias='fmrsplai(7)')
    fgresp_1_: float = Field(..., alias='fgresp(1)')
    fgresp_2_: float = Field(..., alias='fgresp(2)')
    fgresp_3_: float = Field(..., alias='fgresp(3)')
    fgresp_4_: float = Field(..., alias='fgresp(4)')
    fgresp_5_: float = Field(..., alias='fgresp(5)')
    fgresp_6_: float = Field(..., alias='fgresp(6)')
    fgresp_7_: float = Field(..., alias='fgresp(7)')
    no3pref_2_: float = Field(..., alias='no3pref(2)')
    tlaypg: float
    tmix: float
    tmplff: float
    tmplfs: float
    furgdys: float
    flsgres: float
    tmxturn: float
    npp2cs: float
    favail_1_: float = Field(..., alias='favail(1)')
    favail_3_: float = Field(..., alias='favail(3)')
    favail_4_: float = Field(..., alias='favail(4)')
    favail_5_: float = Field(..., alias='favail(5)')
    favail_6_: float = Field(..., alias='favail(6)')


class Tree(BaseModel):
    ALMOND: ALMOND


class NOTILL(BaseModel):
    cultra_1_: float = Field(..., alias='cultra(1)')
    cultra_2_: float = Field(..., alias='cultra(2)')
    cultra_3_: float = Field(..., alias='cultra(3)')
    cultra_4_: float = Field(..., alias='cultra(4)')
    cultra_5_: float = Field(..., alias='cultra(5)')
    cultra_6_: float = Field(..., alias='cultra(6)')
    cultra_7_: float = Field(..., alias='cultra(7)')
    clteff_1_: float = Field(..., alias='clteff(1)')
    clteff_2_: float = Field(..., alias='clteff(2)')
    clteff_3_: float = Field(..., alias='clteff(3)')
    clteff_4_: float = Field(..., alias='clteff(4)')


class Cult(BaseModel):
    NOTILL: NOTILL


class FET11(BaseModel):
    feramt_1_: float = Field(..., alias='feramt(1)')
    feramt_2_: float = Field(..., alias='feramt(2)')
    feramt_3_: float = Field(..., alias='feramt(3)')
    aufert: float
    ferttyp: float
    fertareaf: float
    fertdepth: float
    reft_crnf: float
    t_eighty: float
    crflamda: float
    crf_qten: float
    ninhib: float
    ninhtm: float
    finhib_1_: float = Field(..., alias='finhib(1)')
    finhib_2_: float = Field(..., alias='finhib(2)')
    finhib_3_: float = Field(..., alias='finhib(3)')
    ureakm: float
    ureakui: float
    ureast_1_: float = Field(..., alias='ureast(1)')
    ureast_2_: float = Field(..., alias='ureast(2)')
    frac_nh4: float
    frac_no3: float


class FET12(BaseModel):
    feramt_1_: float = Field(..., alias='feramt(1)')
    feramt_2_: float = Field(..., alias='feramt(2)')
    feramt_3_: float = Field(..., alias='feramt(3)')
    aufert: float
    ferttyp: float
    fertareaf: float
    fertdepth: float
    reft_crnf: float
    t_eighty: float
    crflamda: float
    crf_qten: float
    ninhib: float
    ninhtm: float
    finhib_1_: float = Field(..., alias='finhib(1)')
    finhib_2_: float = Field(..., alias='finhib(2)')
    finhib_3_: float = Field(..., alias='finhib(3)')
    ureakm: float
    ureakui: float
    ureast_1_: float = Field(..., alias='ureast(1)')
    ureast_2_: float = Field(..., alias='ureast(2)')
    frac_nh4: float
    frac_no3: float


class FET13(BaseModel):
    feramt_1_: float = Field(..., alias='feramt(1)')
    feramt_2_: float = Field(..., alias='feramt(2)')
    feramt_3_: float = Field(..., alias='feramt(3)')
    aufert: float
    ferttyp: float
    fertareaf: float
    fertdepth: float
    reft_crnf: float
    t_eighty: float
    crflamda: float
    crf_qten: float
    ninhib: float
    ninhtm: float
    finhib_1_: float = Field(..., alias='finhib(1)')
    finhib_2_: float = Field(..., alias='finhib(2)')
    finhib_3_: float = Field(..., alias='finhib(3)')
    ureakm: float
    ureakui: float
    ureast_1_: float = Field(..., alias='ureast(1)')
    ureast_2_: float = Field(..., alias='ureast(2)')
    frac_nh4: float
    frac_no3: float


class FET14(BaseModel):
    feramt_1_: float = Field(..., alias='feramt(1)')
    feramt_2_: float = Field(..., alias='feramt(2)')
    feramt_3_: float = Field(..., alias='feramt(3)')
    aufert: float
    ferttyp: float
    fertareaf: float
    fertdepth: float
    reft_crnf: float
    t_eighty: float
    crflamda: float
    crf_qten: float
    ninhib: float
    ninhtm: float
    finhib_1_: float = Field(..., alias='finhib(1)')
    finhib_2_: float = Field(..., alias='finhib(2)')
    finhib_3_: float = Field(..., alias='finhib(3)')
    ureakm: float
    ureakui: float
    ureast_1_: float = Field(..., alias='ureast(1)')
    ureast_2_: float = Field(..., alias='ureast(2)')
    frac_nh4: float
    frac_no3: float


class Fert(BaseModel):
    FET11: FET11
    FET12: FET12
    FET13: FET13
    FET14: FET14


class T1(BaseModel):
    auirri: float
    fawhc: float
    irraut: float
    irramt: float


class Irri(BaseModel):
    T1: T1


class PRUNL(BaseModel):
    evntyp: float
    remf_1_: float = Field(..., alias='remf(1)')
    remf_2_: float = Field(..., alias='remf(2)')
    remf_3_: float = Field(..., alias='remf(3)')
    remf_4_: float = Field(..., alias='remf(4)')
    remf_5_: float = Field(..., alias='remf(5)')
    fd_1_: float = Field(..., alias='fd(1)')
    fd_2_: float = Field(..., alias='fd(2)')
    retf_1_1_: float = Field(..., alias='retf(1,1)')
    retf_1_2_: float = Field(..., alias='retf(1,2)')
    retf_1_3_: float = Field(..., alias='retf(1,3)')
    retf_1_4_: float = Field(..., alias='retf(1,4)')
    retf_2_1_: float = Field(..., alias='retf(2,1)')
    retf_2_2_: float = Field(..., alias='retf(2,2)')
    retf_2_3_: float = Field(..., alias='retf(2,3)')
    retf_2_4_: float = Field(..., alias='retf(2,4)')
    retf_3_1_: float = Field(..., alias='retf(3,1)')
    retf_3_2_: float = Field(..., alias='retf(3,2)')
    retf_3_3_: float = Field(..., alias='retf(3,3)')
    retf_3_4_: float = Field(..., alias='retf(3,4)')


class Trem(BaseModel):
    PRUNL: PRUNL


class InputConfigs(BaseModel):
    crop: Dict[str, Any]
    tree: Tree
    grasstree: Dict[str, Any]
    cult: Cult
    fert: Fert
    irri: Irri
    omad: Dict[str, Any]
    graz: Dict[str, Any]
    harv: Dict[str, Any]
    trem: Trem
    fire: Dict[str, Any]


class Outfiles(BaseModel):
    biomass: int
    soil_nitrogen: int
    soil_mean_temperature: int
    soil_max_temperature: int
    soil_min_temperature: int
    soil_temperature_dx: int
    soil_water_content: int
    water_balance: int
    water_filled_pore_space: int
    co2: int
    water_flux_bottom_layers: int
    mrespiration: int
    year_summary: int
    live_carbon: int
    dead_carbon: int
    soil_carbon: int
    system_carbon: int
    trace_gas_fluxes_monthly: int
    denitrification_n2: int
    denitrification_n2o: int
    grespiration: int
    delta_13c_14c: int
    dc_sip: int
    harvest_crop: int
    carbon_flows: int
    carbon_flows_yearly: int
    et: int
    nitrogen_fluxes: int
    summary: int
    methane: int
    fdwfps: int
    ctrlfert: int
    ninhibit: int


class OutputConfigs(BaseModel):
    outvars: List[str]
    outfiles: Outfiles


class Fix(BaseModel):
    adep_1_: float = Field(..., alias='adep(1)')
    adep_2_: float = Field(..., alias='adep(2)')
    adep_3_: float = Field(..., alias='adep(3)')
    adep_4_: float = Field(..., alias='adep(4)')
    adep_5_: float = Field(..., alias='adep(5)')
    adep_6_: float = Field(..., alias='adep(6)')
    adep_7_: float = Field(..., alias='adep(7)')
    adep_8_: float = Field(..., alias='adep(8)')
    adep_9_: float = Field(..., alias='adep(9)')
    adep_10_: float = Field(..., alias='adep(10)')
    agppa: float
    agppb: float
    aneref_1_: float = Field(..., alias='aneref(1)')
    aneref_2_: float = Field(..., alias='aneref(2)')
    aneref_3_: float = Field(..., alias='aneref(3)')
    animpt: float
    awtl_1_: float = Field(..., alias='awtl(1)')
    awtl_2_: float = Field(..., alias='awtl(2)')
    awtl_3_: float = Field(..., alias='awtl(3)')
    awtl_4_: float = Field(..., alias='awtl(4)')
    awtl_5_: float = Field(..., alias='awtl(5)')
    awtl_6_: float = Field(..., alias='awtl(6)')
    awtl_7_: float = Field(..., alias='awtl(7)')
    awtl_8_: float = Field(..., alias='awtl(8)')
    awtl_9_: float = Field(..., alias='awtl(9)')
    awtl_10_: float = Field(..., alias='awtl(10)')
    bgppa: float
    bgppb: float
    co2ppm_1_: float = Field(..., alias='co2ppm(1)')
    co2ppm_2_: float = Field(..., alias='co2ppm(2)')
    co2rmp: float
    damr_1_1_: float = Field(..., alias='damr(1,1)')
    damr_1_2_: float = Field(..., alias='damr(1,2)')
    damr_1_3_: float = Field(..., alias='damr(1,3)')
    damr_2_1_: float = Field(..., alias='damr(2,1)')
    damr_2_2_: float = Field(..., alias='damr(2,2)')
    damr_2_3_: float = Field(..., alias='damr(2,3)')
    damrmn_1_: float = Field(..., alias='damrmn(1)')
    damrmn_2_: float = Field(..., alias='damrmn(2)')
    damrmn_3_: float = Field(..., alias='damrmn(3)')
    dec1_1_: float = Field(..., alias='dec1(1)')
    dec1_2_: float = Field(..., alias='dec1(2)')
    dec2_1_: float = Field(..., alias='dec2(1)')
    dec2_2_: float = Field(..., alias='dec2(2)')
    dec3_1_: float = Field(..., alias='dec3(1)')
    dec3_2_: float = Field(..., alias='dec3(2)')
    dec4: float
    dec5_1_: float = Field(..., alias='dec5(1)')
    dec5_2_: float = Field(..., alias='dec5(2)')
    deck5: float
    dligdf: float
    dresp: float
    edepth: float
    elitst: float
    enrich: float
    favail_1_: float = Field(..., alias='favail(1)')
    favail_3_: float = Field(..., alias='favail(3)')
    favail_4_: float = Field(..., alias='favail(4)')
    favail_5_: float = Field(..., alias='favail(5)')
    favail_6_: float = Field(..., alias='favail(6)')
    fleach_1_: float = Field(..., alias='fleach(1)')
    fleach_2_: float = Field(..., alias='fleach(2)')
    fleach_3_: float = Field(..., alias='fleach(3)')
    fleach_4_: float = Field(..., alias='fleach(4)')
    fleach_5_: float = Field(..., alias='fleach(5)')
    fwloss_1_: float = Field(..., alias='fwloss(1)')
    fwloss_2_: float = Field(..., alias='fwloss(2)')
    fwloss_3_: float = Field(..., alias='fwloss(3)')
    fwloss_4_: float = Field(..., alias='fwloss(4)')
    fxmca: float
    fxmcb: float
    fxmxs: float
    fxnpb: float
    gremb: float
    idef: float
    lhzf_1_: float = Field(..., alias='lhzf(1)')
    lhzf_2_: float = Field(..., alias='lhzf(2)')
    lhzf_3_: float = Field(..., alias='lhzf(3)')
    minlch: float
    nsnfix: float
    ntspm: float
    omlech_1_: float = Field(..., alias='omlech(1)')
    omlech_2_: float = Field(..., alias='omlech(2)')
    omlech_3_: float = Field(..., alias='omlech(3)')
    p1co2a_1_: float = Field(..., alias='p1co2a(1)')
    p1co2a_2_: float = Field(..., alias='p1co2a(2)')
    p1co2b_1_: float = Field(..., alias='p1co2b(1)')
    p1co2b_2_: float = Field(..., alias='p1co2b(2)')
    p2co2_1_: float = Field(..., alias='p2co2(1)')
    p2co2_2_: float = Field(..., alias='p2co2(2)')
    p3co2: float
    pabres: float
    peftxa: float
    peftxb: float
    phesp_1_: float = Field(..., alias='phesp(1)')
    phesp_2_: float = Field(..., alias='phesp(2)')
    phesp_3_: float = Field(..., alias='phesp(3)')
    phesp_4_: float = Field(..., alias='phesp(4)')
    pligst_1_: float = Field(..., alias='pligst(1)')
    pligst_2_: float = Field(..., alias='pligst(2)')
    pmco2_1_: float = Field(..., alias='pmco2(1)')
    pmco2_2_: float = Field(..., alias='pmco2(2)')
    pmnsec_1_: float = Field(..., alias='pmnsec(1)')
    pmnsec_2_: float = Field(..., alias='pmnsec(2)')
    pmnsec_3_: float = Field(..., alias='pmnsec(3)')
    pmntmp: float
    pmxbio: float
    pmxtmp: float
    pparmn_1_: float = Field(..., alias='pparmn(1)')
    pparmn_2_: float = Field(..., alias='pparmn(2)')
    pparmn_3_: float = Field(..., alias='pparmn(3)')
    pprpts_1_: float = Field(..., alias='pprpts(1)')
    pprpts_2_: float = Field(..., alias='pprpts(2)')
    pprpts_3_: float = Field(..., alias='pprpts(3)')
    ps1co2_1_: float = Field(..., alias='ps1co2(1)')
    ps1co2_2_: float = Field(..., alias='ps1co2(2)')
    ps1s3_1_: float = Field(..., alias='ps1s3(1)')
    ps1s3_2_: float = Field(..., alias='ps1s3(2)')
    ps2s3_1_: float = Field(..., alias='ps2s3(1)')
    ps2s3_2_: float = Field(..., alias='ps2s3(2)')
    psecmn_1_: float = Field(..., alias='psecmn(1)')
    psecmn_2_: float = Field(..., alias='psecmn(2)')
    psecmn_3_: float = Field(..., alias='psecmn(3)')
    psecoc1: float
    psecoc2: float
    rad1p_1_1_: float = Field(..., alias='rad1p(1,1)')
    rad1p_2_1_: float = Field(..., alias='rad1p(2,1)')
    rad1p_3_1_: float = Field(..., alias='rad1p(3,1)')
    rad1p_1_2_: float = Field(..., alias='rad1p(1,2)')
    rad1p_2_2_: float = Field(..., alias='rad1p(2,2)')
    rad1p_3_2_: float = Field(..., alias='rad1p(3,2)')
    rad1p_1_3_: float = Field(..., alias='rad1p(1,3)')
    rad1p_2_3_: float = Field(..., alias='rad1p(2,3)')
    rad1p_3_3_: float = Field(..., alias='rad1p(3,3)')
    rcestr_1_: float = Field(..., alias='rcestr(1)')
    rcestr_2_: float = Field(..., alias='rcestr(2)')
    rcestr_3_: float = Field(..., alias='rcestr(3)')
    rictrl: float
    riint: float
    rsplig: float
    seed: float
    spl_1_: float = Field(..., alias='spl(1)')
    spl_2_: float = Field(..., alias='spl(2)')
    strmax_1_: float = Field(..., alias='strmax(1)')
    strmax_2_: float = Field(..., alias='strmax(2)')
    texepp_1_: float = Field(..., alias='texepp(1)')
    texepp_2_: float = Field(..., alias='texepp(2)')
    texepp_3_: float = Field(..., alias='texepp(3)')
    texepp_4_: float = Field(..., alias='texepp(4)')
    texepp_5_: float = Field(..., alias='texepp(5)')
    texesp_1_: float = Field(..., alias='texesp(1)')
    texesp_3_: float = Field(..., alias='texesp(3)')
    teff_1_: float = Field(..., alias='teff(1)')
    teff_2_: float = Field(..., alias='teff(2)')
    weff_1_: float = Field(..., alias='weff(1)')
    weff_2_: float = Field(..., alias='weff(2)')
    tmelt_1_: float = Field(..., alias='tmelt(1)')
    tmelt_2_: float = Field(..., alias='tmelt(2)')
    varat11_1_1_: float = Field(..., alias='varat11(1,1)')
    varat11_2_1_: float = Field(..., alias='varat11(2,1)')
    varat11_3_1_: float = Field(..., alias='varat11(3,1)')
    varat11_1_2_: float = Field(..., alias='varat11(1,2)')
    varat11_2_2_: float = Field(..., alias='varat11(2,2)')
    varat11_3_2_: float = Field(..., alias='varat11(3,2)')
    varat11_1_3_: float = Field(..., alias='varat11(1,3)')
    varat11_2_3_: float = Field(..., alias='varat11(2,3)')
    varat11_3_3_: float = Field(..., alias='varat11(3,3)')
    varat12_1_1_: float = Field(..., alias='varat12(1,1)')
    varat12_2_1_: float = Field(..., alias='varat12(2,1)')
    varat12_3_1_: float = Field(..., alias='varat12(3,1)')
    varat12_1_2_: float = Field(..., alias='varat12(1,2)')
    varat12_2_2_: float = Field(..., alias='varat12(2,2)')
    varat12_3_2_: float = Field(..., alias='varat12(3,2)')
    varat12_1_3_: float = Field(..., alias='varat12(1,3)')
    varat12_2_3_: float = Field(..., alias='varat12(2,3)')
    varat12_3_3_: float = Field(..., alias='varat12(3,3)')
    varat21_1_1_: float = Field(..., alias='varat21(1,1)')
    varat21_2_1_: float = Field(..., alias='varat21(2,1)')
    varat21_3_1_: float = Field(..., alias='varat21(3,1)')
    varat21_1_2_: float = Field(..., alias='varat21(1,2)')
    varat21_2_2_: float = Field(..., alias='varat21(2,2)')
    varat21_3_2_: float = Field(..., alias='varat21(3,2)')
    varat21_1_3_: float = Field(..., alias='varat21(1,3)')
    varat21_2_3_: float = Field(..., alias='varat21(2,3)')
    varat21_3_3_: float = Field(..., alias='varat21(3,3)')
    varat22_1_1_: float = Field(..., alias='varat22(1,1)')
    varat22_2_1_: float = Field(..., alias='varat22(2,1)')
    varat22_3_1_: float = Field(..., alias='varat22(3,1)')
    varat22_1_2_: float = Field(..., alias='varat22(1,2)')
    varat22_2_2_: float = Field(..., alias='varat22(2,2)')
    varat22_3_2_: float = Field(..., alias='varat22(3,2)')
    varat22_1_3_: float = Field(..., alias='varat22(1,3)')
    varat22_2_3_: float = Field(..., alias='varat22(2,3)')
    varat22_3_3_: float = Field(..., alias='varat22(3,3)')
    varat3_1_1_: float = Field(..., alias='varat3(1,1)')
    varat3_2_1_: float = Field(..., alias='varat3(2,1)')
    varat3_3_1_: float = Field(..., alias='varat3(3,1)')
    varat3_1_2_: float = Field(..., alias='varat3(1,2)')
    varat3_2_2_: float = Field(..., alias='varat3(2,2)')
    varat3_3_2_: float = Field(..., alias='varat3(3,2)')
    varat3_1_3_: float = Field(..., alias='varat3(1,3)')
    varat3_2_3_: float = Field(..., alias='varat3(2,3)')
    varat3_3_3_: float = Field(..., alias='varat3(3,3)')
    vlosse: float
    vlossg: float
    xefcltef: float
    maxcltef: float
    fldn2d: float
    fln2or: float
    co2ch4: float
    mxch4f: float
    frexud: float
    aeh: float
    deh: float
    behfl: float
    behdr: float
    methzr: float
    wfdryt: float
    tplen: float
    plmfdd: float
    plxfdd: float
    ptrlyr: float
    tnpsif: float
    dpsfdm: float
    dpsfdx: float
    tndrrl: float


class Sitepar(BaseModel):
    usexdrvrs: float
    sublimscale: float
    reflec: float
    albedo: float
    dmpflux: float
    hours_rain: float
    drainlag: float
    hpotdeep: float
    ksatdeep: float
    tbotmn: float
    tbotmx: float
    dmp: float
    timlag: float
    ncoeff: float
    jdaystart: float
    jdayend: float
    n2oadjust_fc: float
    n2oadjust_wp: float
    maxnitamt: float
    snowflag: float
    netmn_to_no3: float
    wfpsdnitadj: float
    n2n2oadj: float
    elevation: float
    slope: float
    aspect: float
    ehoriz: float
    whoriz: float
    sradadj_1_: float = Field(..., alias='sradadj[1]')
    sradadj_2_: float = Field(..., alias='sradadj[2]')
    sradadj_3_: float = Field(..., alias='sradadj[3]')
    sradadj_4_: float = Field(..., alias='sradadj[4]')
    sradadj_5_: float = Field(..., alias='sradadj[5]')
    sradadj_6_: float = Field(..., alias='sradadj[6]')
    sradadj_7_: float = Field(..., alias='sradadj[7]')
    sradadj_8_: float = Field(..., alias='sradadj[8]')
    sradadj_9_: float = Field(..., alias='sradadj[9]')
    sradadj_10_: float = Field(..., alias='sradadj[10]')
    sradadj_11_: float = Field(..., alias='sradadj[11]')
    sradadj_12_: float = Field(..., alias='sradadj[12]')


class ExtraConfigs(BaseModel):
    fix: Fix
    sitepar: Sitepar


class Data(BaseModel):
    field: str
    description: str
    locations: Locations
    created_at: str
    scenarios: Scenarios
    site_configs: SiteConfigs
    input_configs: InputConfigs
    output_configs: OutputConfigs
    extra_configs: ExtraConfigs


class Model(BaseModel):
    data: Data
